package business;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

//Each Instance of this class should be a note doc in notes collection when persisted to mongo database
@Document(collection = "notes")
public class Note {
	@Id
	private String id;//This doc identifiable by Id type string thats autogenerated by Mongo when doc is persisted 
	private String week;
	private String course;
	private String courseSection;
	private String fileName;
	private String filePath;
	
	public Note(String week, String course, String courseSection) {
		super();
		this.week = week;
		this.course = course;
		this.courseSection = courseSection;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getWeek() {
		return week;
	}

	public void setWeek(String week) {
		this.week = week;
	}

	public String getCourse() {
		return course;
	}

	public void setCourse(String course) {
		this.course = course;
	}

	public String getCourseSection() {
		return courseSection;
	}

	public void setCourseSection(String courseSection) {
		this.courseSection = courseSection;
	}

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getFilePath() {
		return filePath;
	}

	public void setFilePath(String filePath) {
		this.filePath = filePath;
	}
	
}
